language: python
python:
    - "2.7"

cache:
  directories:
    - $HOME/.cache

sudo: required
dist: trusty

compiler:
    - gcc

addons:
  apt:
    packages:
      - libpng12-dev
      - libgdal1-dev
      - pkg-config
      - libnetcdf-dev

before_install:
  # Fix a travis/boto issue.  See
  # https://github.com/travis-ci/travis-ci/issues/7940
  - sudo rm -f /etc/boto.cfg

  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "3" ]; then export PY3="true"; else export PY2="true"; fi

  - export DEPLOY=true

  - GIRDER_BRANCH="2.x-maintenance"
  - DATABASE_ASSETSTORE_VERSION="73651be9d133178dc1a791c7bec8b20071e08664"

  # Install GDAL 2
  - export CPLUS_INCLUDE_PATH=/usr/include/gdal
  - export C_INCLUDE_PATH=/usr/include/gdal
  - sudo add-apt-repository -y ppa:ubuntugis/ppa && sudo apt-get update
  - sudo apt-get install -y gdal-bin libgdal-dev
  - gdal-config --version

  - MAIN_PATH=$PWD
  - BUILD_PATH=$HOME/build
  - mkdir -p $BUILD_PATH

  - nvm install v6
  - nvm use v6
  - npm install -g npm

  - export GIRDER_SOURCE_DIR=$BUILD_PATH/girder
  - rm -rf $GIRDER_SOURCE_DIR
  - git clone https://github.com/girder/girder.git $GIRDER_SOURCE_DIR && git -C $GIRDER_SOURCE_DIR checkout -b $GIRDER_BRANCH
  # - ln -sf $MAIN_PATH $GIRDER_SOURCE_DIR/plugins/
  - cp -r $MAIN_PATH $GIRDER_SOURCE_DIR/plugins/
  - cp $GIRDER_SOURCE_DIR/plugins/minerva/server/conf/minerva.dist.cfg $GIRDER_SOURCE_DIR/plugins/minerva/server/conf/minerva.local.cfg
  - cp $GIRDER_SOURCE_DIR/plugins/minerva/server/jobs/bsve.json.in $GIRDER_SOURCE_DIR/plugins/minerva/server/jobs/bsve.json

  - CACHE=$HOME/.cache CMAKE_VERSION=3.4.3 CMAKE_SHORT_VERSION=3.4 source $GIRDER_SOURCE_DIR/scripts/install_cmake.sh
  - cmake --version

  - export MONGO_VERSION=3.0.7
  - export PY_COVG="ON"
  - CACHE=$HOME/.cache source $GIRDER_SOURCE_DIR/scripts/install_mongo.sh
  - mkdir /tmp/db
  - mongod --dbpath=/tmp/db >/dev/null 2>/dev/null &
  - mongod --version

  # install database_assetstore plugin
  - DB_ASSETSTORE_DIR="${GIRDER_SOURCE_DIR}/plugins/database_assetstore"
  - git clone https://github.com/OpenGeoscience/database_assetstore.git "${DB_ASSETSTORE_DIR}" && git -C "${DB_ASSETSTORE_DIR}" checkout $DATABASE_ASSETSTORE_VERSION
  - pip install -r "${DB_ASSETSTORE_DIR}/requirements.txt" -U
    
  # install girder_ktile plugin
  - GIRDER_KTILE_DIR="${GIRDER_SOURCE_DIR}/plugins/girder_ktile"
  - git clone https://github.com/OpenGeoscience/girder_ktile.git "${GIRDER_KTILE_DIR}"
  - pip install -r "${GIRDER_KTILE_DIR}/requirements.txt" -U

  - npm install -g npm
  - npm install -g npm-install-retry
  - npm --version

  - pip install --no-cache-dir -U pip virtualenv setuptools

install:
  - cd $GIRDER_SOURCE_DIR
  - pip install --no-cache-dir -U -r requirements-dev.txt -e .
  - pip install -r $MAIN_PATH/requirements.txt
  - pip install -r $MAIN_PATH/requirements-dev.txt

  - npm-install-retry
  - BABEL_ENV=cover NYC_CWD=$MAIN_PATH girder-install web --plugins=minerva,gravatar,jobs,database_assetstore --dev

  # replace girder's ctest config with minerva's
  - cp "$GIRDER_SOURCE_DIR/plugins/minerva/cmake/CTestConfig.cmake" "$GIRDER_SOURCE_DIR/."

script:
  - export GIRDER_SOURCE_DIR=$BUILD_PATH/girder
  - export GIRDER_BUILD_DIR=$BUILD_PATH/_build
  - mkdir -p $GIRDER_BUILD_DIR
  - cd $GIRDER_BUILD_DIR
  
  - JASMINE_TIMEOUT=15000 ctest -S "$GIRDER_SOURCE_DIR/plugins/minerva/cmake/travis_continuous.cmake" -VV || true
  - if [ -f $GIRDER_BUILD_DIR/test_failed ] ; then false ; fi
