language: python
python:
    - "2.7"
#    - "3.4" For now romanesco doesn't support Python 3

cache:
  directories:
  - $HOME/virtualenv/python2.7.9
  - $HOME/.cache/pip
  - $HOME/build/girder/node_modules
  - $HOME/build/girder/plugins/minerva/node_modules
  - $HOME/spark-1.3.1-bin-hadoop2.4

sudo: false

compiler:
    - gcc

addons:
  apt:
    packages:
    - libfreetype6-dev
    - libpng12-dev
    - libgdal1-dev
    - pkg-config
    - libnetcdf-dev

before_install:
    # move node_modules caches so that git clone girder completes
    - mv $HOME/build/girder/node_modules $HOME/build/girder_node_modules_cache
    - mv $HOME/build/girder/plugins/minerva/node_modules $HOME/build/minerva_node_modules_cache

    # minerva has been cloned to Kitware/minerva by travis
    # girder needs to be cloned and then minerva moved under girder
    - cd $HOME/build
    # remove existing girder dir, it remains from caching operations
    - rm -rf girder
    - git clone https://github.com/girder/girder.git
    - mv Kitware/minerva girder/plugins

    # clone romanesco
    - cd $HOME/build/girder/plugins
    - git clone https://github.com/Kitware/romanesco.git
    - cd $HOME/build

    # move the node_modules caches
    - mv $HOME/build/girder_node_modules_cache $HOME/build/girder/node_modules
    - mv $HOME/build/minerva_node_modules_cache $HOME/build/girder/plugins/minerva/node_modules

    - cd girder
    # copy the placeholder bsve credentials, needed even though we mock bsve api calls
    - cp plugins/minerva/server/utility/bsve/bsve.json.in plugins/minerva/server/utility/bsve/bsve.json

    # Show the memory state; this lets us more quickly determine when the
    # travis environment is bad
    - vmstat
    - export IGNORE_PLUGINS=celery_jobs,geospatial,google_analytics,hdfs_assetstore,jquery_widgets,metadata_extractor,mongo_search,oauth,provenance,thumbnails,user_quota,vega;
    - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "3" ]; then export PY3="true"; else export PY2="true"; fi
    - if [ -n "${PY3}" ]; then export MONGO_VERSION=3.0.2; export PY_COVG="OFF"; else export MONGO_VERSION=2.6.9; export PY_COVG="ON"; export DEPLOY=true; fi

    # mongo
    - pushd "${HOME}"
    - curl "https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-${MONGO_VERSION}.tgz" | gunzip -c | tar x
    - cd mongodb-*/bin && export PATH="${PWD}:${PATH}"
    - popd
    - mkdir /tmp/db
    - mongod --dbpath=/tmp/db >/dev/null 2>/dev/null &
    - mongod --version

    # cmake
    - cd $HOME
    - curl "http://www.cmake.org/files/v3.1/cmake-3.1.0-Linux-x86_64.tar.gz" | gunzip -c | tar x
    - cd cmake-*/bin && export PATH="${PWD}:${PATH}"
    - cmake --version

    # install spark
    - cd $HOME
    - wget http://www.scala-lang.org/files/archive/scala-2.10.5.tgz
    - tar xzvf scala-2.10.5.tgz -C ~
    - export SCALA_HOME=$HOME/scala-2.10.5
    - export PATH=$PATH:$SCALA_HOME/bin
    # spark may be cached
    - export SPARK_HOME=$HOME/spark-1.3.1-bin-hadoop2.4
    - if [ ! -d $SPARK_HOME/sbin/start-master.sh ]; then wget http://psg.mtu.edu/pub/apache/spark/spark-1.3.1/spark-1.3.1-bin-hadoop2.4.tgz; fi
    - if [ ! -d $SPARK_HOME/sbin/start-master.sh ]; then tar xzvf spark-1.3.1-bin-hadoop2.4.tgz -C ~; fi
    - export SPARK_MASTER_IP=localhost
    - $SPARK_HOME/sbin/start-master.sh
    - sleep 3
    - $SPARK_HOME/sbin/start-slave.sh worker1 spark://localhost:7077

    # global npm install
    - npm install -g npm@next
    - npm --version

install:
    - cd $HOME/build/girder
    - scripts/InstallPythonRequirements.py --mode=dev --ignore-plugins=${IGNORE_PLUGINS}
    - npm install grunt grunt-cli
    - pushd plugins/minerva

    # install minerva npm dependencies
    - npm install
    - popd

    # install girder npm dependencies and grunt at top level
    - npm install

script:
    - mkdir _build
    - cd _build
    - cmake -DPYTHON_COVERAGE:BOOL=${PY_COVG} -DPYTHON_VERSION:STRING=${TRAVIS_PYTHON_VERSION} -D SPARK_TEST_MASTER_URL:STRING="spark://localhost:7077" ..
    - JASMINE_TIMEOUT=15000 ctest -R minerva -VV
