---
galaxy_info:
  author: Kitware, Inc.
  description: Install the Cumulus package and related Girder plugins
  company: Kitware, Inc.

  license: Apache
  min_ansible_version: 2.0

  platforms:
  - name: Ubuntu
    versions:
    - trusty

  galaxy_tags:
    - minerva
    - girder

dependencies:
  - role: girder
