---
  - name: add nodejs ppa
    apt_repository: repo='ppa:chris-lea/node.js'
    sudo: yes

  - name: apt | cache | update
    apt: update_cache=yes
    when: do_install|bool

  - name: girder | deps | install
    apt: name={{ item }} state=present update_cache=yes
    with_items:
      - curl
      - g++
      - git
      - libffi-dev
      - make
      - python-dev
      - python-pip
      - python-virtualenv
      - nodejs
    when: do_install|bool

  - name: girder | service | stop
    service:
        name: girder
        state: stopped
    ignore_errors: true
    when: stop_services|bool


  - name: girder | install root | delete
    file:
        path: "{{ girder_install_root }}"
        state: absent
    when: remove_install_root|bool

  - name: girder | data root | delete
    file:
        path: "{{ girder_data_root }}"
        state: absent
    when: remove_data_root|bool

  - name: girder | install parent | create
    file:
        path: "{{ girder_install_parent }}"
        state: directory
    when: do_install|bool

  - name: girder | data root | create
    file:
        path: "{{ girder_data_root }}"
        state: directory
        mode: 0755
    when: do_install|bool

  - name: girder | repo | sync
    command: >
        rsync -avz --exclude=.git
        "{{ girder_git_work_dir }}/"
        "{{ girder_install_root }}"
    when: do_install|bool

  - name: girder | log | perms | set
    file:
        path: "{{ girder_install_root }}/logs"
        mode: 0755
        state: directory
    when: do_install|bool

  - name: Install editable version of girder
    pip:
      chdir: "{{ girder_install_root }}"
      extra_args: "-e"
      name: "."
      virtualenv: "{{venv_root}}"

  - name: Install frontend assets
    shell: ". {{venv_root}}/bin/activate && girder-install web"
    args:
      chdir: "{{ girder_install_root }}"


  - name: Install editable version of girder-client
    pip:
      chdir: "{{ girder_install_root }}/clients/python"
      extra_args: "-e"
      name: "."


  - name: grunt-cli | install
    npm:
        name: grunt-cli
        global: yes
    when: do_install|bool

  - name: girder | conf | girder.local.cfg | generate
    template:
        src: girder.local.cfg.j2
        dest: "{{ girder_install_root }}/girder/conf/girder.local.cfg"
        mode: 0644
    when: do_install|bool

  - name: girder | conf | owner | set
    file:
        recurse: yes
        path: "{{ girder_install_root }}"
        group: "{{ girder_group }}"
        mode: 0755
        owner: "{{ girder_user }}"
    when: do_install|bool

  - name: girder | virtualenv | owner | set
    file:
        recurse: yes
        path: "{{ venv_root }}"
        owner: "{{ girder_user }}"
        group: "{{ girder_group }}"
        mode: 0755
    when: do_install|bool
