- hosts: minerva_dataservices
  remote_user: vagrant
  roles:
     - common
     - {role: geerlingguy.redis, sudo: yes}
     - zenoamaro.supervisord
     - postgres_postgis
     - geoserver
     - nginx
     - uwsgi
     - geonode
     - dataqs
