###
# Installs nginx
#
---
- name: add repository for latest nginx stable
  apt_repository: repo='ppa:nginx/stable'
  sudo: yes

- name: ensure apt cache is up to date
  apt: update_cache=yes
  sudo: yes

- name: ensure nginx is installed
  apt: name=nginx 
  sudo: yes

- name: write nginx configuration for multiple subdomains
  template: src=nginx.conf.j2 dest=/etc/nginx/sites-available/default
  sudo: yes
  notify:
    - restart nginx
